import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, options?: { [key: string]: string | number }) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export { LanguageContext };

interface LanguageProviderProps {
  children: ReactNode;
}

// Translation dictionaries
const translations = {
  en: {
    // Common
    'common.back': 'Back',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.orders': 'Orders',
    'nav.inventory': 'Inventory',
    'nav.workers': 'Workers',
    'nav.calendar': 'Calendar',
    'nav.production': 'Production Flow',
    'nav.stations': 'Stations',
    'nav.analytics': 'Analytics',
    'nav.advanced': 'Advanced Features',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    
    // Settings Page
    'settings.title': 'Settings',
    'settings.description': 'Manage your application preferences and configurations',
    'settings.notifications.title': 'Notification Preferences',
    'settings.notifications.description': 'Configure how you receive notifications',
    'settings.notifications.email.title': 'Email Notifications',
    'settings.notifications.email.description': 'Receive order and system updates via email',
    'settings.notifications.email.orderUpdates': 'Order Updates',
    'settings.notifications.email.orderUpdatesDesc': 'Get notified about order status changes',
    'settings.notifications.app.title': 'In-App Notifications',
    'settings.notifications.app.description': 'Show notifications within the application',
    'settings.notifications.app.inApp': 'In-App Notifications',
    'settings.notifications.app.inAppDesc': 'Display notifications in the application interface',
    'settings.notifications.sms.title': 'SMS Notifications',
    'settings.notifications.sms.description': 'Receive urgent updates via SMS',
    'settings.notifications.sms.urgent': 'Urgent Updates',
    'settings.notifications.sms.urgentDesc': 'Get SMS for critical updates',
    'settings.general.title': 'General Settings',
    'settings.general.description': 'Configure application preferences',
    'settings.general.language.title': 'Language',
    'settings.general.timezone.title': 'Timezone',
    'settings.general.deliveryBuffer.title': 'Delivery Buffer',
    'settings.general.deliveryBuffer.description': 'Additional days to add to estimated delivery dates',
    'settings.general.deliveryBuffer.days': 'days',
    'settings.security.title': 'Security & Privacy',
    'settings.security.description': 'Manage your account security settings',
    'settings.security.password.title': 'Password',
    'settings.security.password.lastChanged': 'Last changed',
    'settings.security.password.days': 'days ago',
    'settings.security.password.change': 'Change Password',
    'settings.security.twoFactor.title': 'Two-Factor Authentication',
    'settings.security.twoFactor.description': 'Add an extra layer of security to your account',
    'settings.security.twoFactor.enable': 'Enable 2FA',
    'settings.appearance.title': 'Appearance',
    'settings.appearance.description': 'Customize the look and feel',
    'settings.appearance.theme.title': 'Theme',
    'settings.appearance.theme.light': 'Light',
    'settings.appearance.theme.dark': 'Dark',
    'settings.appearance.theme.auto': 'Auto',
    'settings.appearance.theme.description': 'Choose how the application looks.',
    'settings.appearance.primaryColor.title': 'Primary Color',
    'settings.appearance.primaryColor.description': 'Pick an accent color for the UI.',
    'settings.appearance.preview.title': 'Theme Preview',
    'settings.appearance.preview.description': 'See how the selected theme looks',
    'settings.appearance.preview.cardTitle': 'Sample Card',
    'settings.appearance.preview.cardDescription': 'This is how cards will appear with the selected theme.',
    'settings.appearance.preview.successButton': 'Primary Button',
    'settings.appearance.preview.secondaryButton': 'Secondary Button',
    'settings.actions.save': 'Save All Changes',
    'settings.actions.reset': 'Reset to Default',
    'settings.actions.export': 'Export Settings',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back!',
    'dashboard.overview': 'System Overview',
    'dashboard.totalOrders': 'Total Orders',
    'dashboard.activeWorkers': 'Active Workers',
    'dashboard.pendingTasks': 'Pending Tasks',
    'dashboard.completedToday': 'Completed Today',
    'dashboard.revenue': 'Monthly Revenue',
    'dashboard.productivity': 'Productivity',
    'dashboard.recentOrders': 'Recent Orders',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.alerts': 'System Alerts',
    'dashboard.importSuccess': 'Imported successfully!',
    'dashboard.importing': 'Importing...',
    'dashboard.importFromWooCommerce': 'Import from WooCommerce',
    'dashboard.additionalStats': 'Additional Stats',
    'dashboard.clients': 'Clients',
    'dashboard.materials': 'Materials',
    'dashboard.unpaidInvoices': 'Unpaid Invoices',
    'dashboard.completionRate': 'Completion Rate',
    'dashboard.importResults': 'Imported: {{customers}} customers, {{products}} products, {{orders}} orders',
    'dashboard.importFailed': 'Failed to import from WooCommerce',
    'dashboard.orderStatus.pending': 'Pending',
    'dashboard.orderStatus.inProgress': 'In Progress',
    'dashboard.orderStatus.completed': 'Completed',
    
    // Orders
    'orders.title': 'Order Management',
    'orders.subtitle': 'View and manage all customer orders',
    'orders.newOrder': 'New Order',
    'orders.searchPlaceholder': 'Search orders...',
    'orders.filter.all': 'All Statuses',
    'orders.filter.pending': 'Pending',
    'orders.filter.in_progress': 'In Progress',
    'orders.filter.completed': 'Completed',
    'orders.filter.cancelled': 'Cancelled',
    'orders.card.worker': 'Worker: {workerName}',
    'orders.card.priority.urgent': 'Urgent',
    'orders.card.priority.high': 'High',
    'orders.card.priority.medium': 'Medium',
    'orders.card.priority.low': 'Low',
    'orders.empty.title': 'No Orders Found',
    'orders.empty.subtitle': 'Get started by creating a new order.',
    'orders.createModal.title': 'Create New Order',
    'orders.editModal.title': 'Edit Order',
    'orders.form.title.label': 'Order Title',
    'orders.form.client.label': 'Client',
    'orders.form.client.placeholder': 'Select a client',
    'orders.form.category.label': 'Category',
    'orders.form.category.placeholder': 'Select a category',
    'orders.form.worker.label': 'Assigned Worker',
    'orders.form.worker.placeholder': 'Select a worker',
    'orders.form.priority.label': 'Priority',
    'orders.form.cost.label': 'Total Cost',
    'orders.form.startDate.label': 'Start Date',
    'orders.form.dueDate.label': 'Due Date',
    'orders.form.description.label': 'Description',
    'orders.form.createButton': 'Create Order',
    'orders.form.updateButton': 'Save Changes',
    'orders.form.cancelButton': 'Cancel',
    'orders.toast.createSuccess': 'Order created successfully.',
    'orders.toast.createError': 'Error creating order.',
    'orders.toast.updateSuccess': 'Order updated successfully.',
    'orders.toast.updateError': 'Error updating order.',
    'orders.toast.deleteSuccess': 'Order deleted successfully.',
    'orders.toast.deleteError': 'Error deleting order.',
    'orders.toast.statusUpdateSuccess': 'Status updated successfully.',
    'orders.toast.statusUpdateError': 'Error updating status.',
    'orders.deleteConfirm': 'Are you sure you want to delete this order?',
    'orders.status.pending': 'Pending',
    'orders.status.in_progress': 'In Progress',
    'orders.status.completed': 'Completed',
    'orders.status.cancelled': 'Cancelled',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.subtitle': 'Track and manage your materials and stock levels.',
    'inventory.addItem': 'Add New Item',
    'inventory.totalItems': 'Total Items',
    'inventory.lowStock': 'Low Stock',
    'inventory.outOfStock': 'Out of Stock',
    'inventory.stockValue': 'Total Stock Value',
    'inventory.searchPlaceholder': 'Search by name or SKU...',
    'inventory.allCategories': 'All Categories',
    'inventory.allStatuses': 'All Statuses',
    'inventory.lowStockStatus': 'Low Stock',
    'inventory.outOfStockStatus': 'Out of Stock',
    'inventory.table.image': 'Image',
    'inventory.table.name': 'Name',
    'inventory.table.sku': 'SKU',
    'inventory.table.category': 'Category',
    'inventory.table.quantity': 'Quantity',
    'inventory.table.status': 'Status',
    'inventory.table.actions': 'Actions',
    'inventory.noResults': 'No materials found. Try adjusting your filters.',
    'inventory.modal.addTitle': 'Add New Inventory Item',
    'inventory.modal.editTitle': 'Edit Inventory Item',
    'inventory.form.name': 'Material Name',
    'inventory.form.category': 'Category',
    'inventory.form.selectCategory': 'Select a category',
    'inventory.form.description': 'Description',
    'inventory.form.sku': 'SKU (Stock Keeping Unit)',
    'inventory.form.unit': 'Unit (e.g., meters, pcs)',
    'inventory.form.quantity': 'Quantity on Hand',
    'inventory.form.cost': 'Cost per Unit',
    'inventory.form.supplier': 'Supplier',
    'inventory.form.reorderLevel': 'Re-order Level',
    'inventory.form.location': 'Storage Location',
    'inventory.form.imageUrl': 'Image URL',
    'common.error': 'An error occurred. Please try again.',
    'common.success': 'Operation successful!',
    'common.deleteConfirm': 'Are you sure you want to delete this item?',
    'common.available': 'Available',
    'common.cancel': 'Cancel',
    'common.update': 'Update',
    'common.save': 'Save',
    'invoices.title': 'Invoices Management',
    'invoices.subtitle': 'Create and track invoices and payments',
    'invoices.new': 'New Invoice',
    'invoices.total': 'Total Invoices',
    'invoices.paid': 'Amount Paid',
    'invoices.pending': 'Pending Amount',
    'invoices.overdue': 'Overdue Invoices',
    'invoices.searchPlaceholder': 'Search invoices...',
    'invoices.allStatuses': 'All Statuses',
    'invoices.status.draft': 'Draft',
    'invoices.status.sent': 'Sent',
    'invoices.status.paid': 'Paid',
    'invoices.status.overdue': 'Overdue',
    'invoices.status.cancelled': 'Cancelled',
    'invoices.issued': 'Issued: {date}',
    'invoices.due': 'Due: {date}',
    'invoices.amount': 'Amount: ${amount}',
    'invoices.tax': 'Tax: ${amount}',
    'invoices.totalAmount': 'Total: ${amount}',
    'invoices.noInvoices': 'No invoices found',
    'invoices.createFirst': 'Start by creating a new invoice',
    'invoices.modal.addTitle': 'Create New Invoice',
    'invoices.modal.editTitle': 'Edit Invoice',
    'invoices.form.client': 'Client',
    'invoices.form.selectClient': 'Select Client',
    'invoices.form.amount': 'Amount',
    'invoices.form.taxAmount': 'Tax Amount',
    'invoices.form.issueDate': 'Issue Date',
    'invoices.form.dueDate': 'Due Date',
    'invoices.form.notes': 'Notes',
    'invoices.form.create': 'Create Invoice',
    'invoices.form.save': 'Save Changes',
    'invoices.error.load': 'Failed to load data',
    'invoices.success.create': 'Invoice created successfully',
    'invoices.error.create': 'Failed to create invoice',
    'invoices.success.update': 'Invoice updated successfully',
    'invoices.error.update': 'Failed to update invoice',
    'invoices.confirm.delete': 'Are you sure you want to delete this invoice?',
    'invoices.success.delete': 'Invoice deleted successfully',
    'invoices.error.delete': 'Failed to delete invoice',
    'invoices.success.statusUpdate': 'Invoice status updated successfully',
    'invoices.error.statusUpdate': 'Failed to update invoice status',
    'notifications.title': '{departmentName} Notifications',
    'notifications.subtitle': 'Stay updated with {departmentDescription} activities',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.markAllAsRead': 'Mark all as read',
    'notifications.viewDetails': 'View details',
    'notifications.markAsRead': 'Mark as read',
    'notifications.noNotifications': 'No notifications found',
    'notifications.noNotificationsFor': 'No notifications for {departmentName}',
    'orderDetails.title': 'Order #{orderId}',
    'orderDetails.subtitle': '{departmentName} • {clientName}',
    'orderDetails.print': 'Print',
    'orderDetails.edit': 'Edit Order',
    'orderDetails.save': 'Save Changes',
    'orderDetails.backToOrders': 'Back to Orders',
    'orderDetails.status.received': 'Received',
    'orderDetails.status.in_progress': 'In Progress',
    'orderDetails.status.completed': 'Completed',
    'orderDetails.status.cancelled': 'Cancelled',
    'orderDetails.created_at': 'Created {date}',
    'orderDetails.progress': 'Order Progress',
    'orderDetails.tab.details': 'Order Details',
    'orderDetails.tab.timeline': 'Timeline',
    'orderDetails.tab.notes': 'Notes',
    'orderDetails.measurements': 'Measurements',
    'orderDetails.orderInfo': 'Order Information',
    'orderDetails.productType': 'Product Type',
    'orderDetails.deadline': 'Deadline',
    'orderDetails.department': 'Department',
    'orderDetails.timeline': 'Timeline',
    'orderDetails.created': 'Created',
    'orderDetails.lastUpdated': 'Last Updated',
    'orderDetails.daysRemaining': 'Days Remaining',
    'orderDetails.days': '{count} days',
    'orderDetails.timeline.created': 'Order Created',
    'orderDetails.timeline.productionStarted': 'Production Started',
    'orderDetails.timeline.completed': 'Order Completed',
    'orderDetails.notes.label': 'Order Notes',
    'orderDetails.notes.placeholder': 'Add notes about this order...',
    'orderDetails.notes.save': 'Save Notes',
    'orderDetails.clientInfo': 'Client Information',
    'orderDetails.clientName': 'Client Name',
    'orderDetails.phoneNumber': 'Phone Number',
    'orderDetails.emailAddress': 'Email Address',
    'orderDetails.quickActions': 'Quick Actions',
    'orderDetails.scheduleFitting': 'Schedule Fitting',
    'orderDetails.deleteOrder': 'Delete Order',
    'orderDetails.stats': 'Order Statistics',
    'orderDetails.daysInProduction': 'Days in Production',
    'orderDetails.priority': 'Priority',
    'orderDetails.priority.normal': 'Normal',
    'orderDetails.notFound.title': 'Order Not Found',
    'orderDetails.notFound.message': "The order you're looking for doesn't exist or has been removed.",
    'orderDetails.toast.print': 'Print dialog opened',
    'orderDetails.toast.updated': 'Order updated successfully',
    'orderDetails.toast.deleted': 'Order deleted successfully',
    'orderDetails.confirm.delete': 'Are you sure you want to delete this order? This action cannot be undone.',
    
    // Order More Inventory
    'orderMoreInventory.title': 'Order More - {itemName}',
    'orderMoreInventory.subtitle': '{departmentName} • Create purchase order',
    'orderMoreInventory.backToInventory': 'Back to Inventory',
    'orderMoreInventory.notFound.title': 'Item Not Found',
    'orderMoreInventory.notFound.message': "The inventory item you're looking for doesn't exist.",
    'orderMoreInventory.form.title': 'Purchase Order Details',
    'orderMoreInventory.form.quantity': 'Quantity to Order *',
    'orderMoreInventory.form.priority': 'Priority Level',
    'orderMoreInventory.form.priority.normal': 'Normal',
    'orderMoreInventory.form.priority.urgent': 'Urgent',
    'orderMoreInventory.form.priority.express': 'Express',
    'orderMoreInventory.form.supplier': 'Supplier *',
    'orderMoreInventory.form.supplier.placeholder': 'Supplier name',
    'orderMoreInventory.form.unitPrice': 'Unit Price',
    'orderMoreInventory.form.expectedDelivery': 'Expected Delivery Date',
    'orderMoreInventory.form.notes': 'Order Notes',
    'orderMoreInventory.form.notes.placeholder': 'Any special instructions or notes for this order...',
    'orderMoreInventory.form.cancel': 'Cancel',
    'orderMoreInventory.form.submit': 'Create Purchase Order',
    'orderMoreInventory.form.submitting': 'Creating Order...',
    'orderMoreInventory.summary.item.title': 'Item Summary',
    'orderMoreInventory.summary.item.currentStock': 'Current Stock:',
    'orderMoreInventory.summary.item.minLevel': 'Min Level:',
    'orderMoreInventory.summary.item.department': 'Department:',
    'orderMoreInventory.summary.item.lowStock': 'Low Stock Alert',
    'orderMoreInventory.summary.item.lowStock.message': 'Current stock is below minimum level',
    'orderMoreInventory.summary.order.title': 'Order Summary',
    'orderMoreInventory.summary.order.quantity': 'Quantity:',
    'orderMoreInventory.summary.order.unitPrice': 'Unit Price:',
    'orderMoreInventory.summary.order.totalCost': 'Total Cost:',
    'orderMoreInventory.tips.title': 'Order Tips',
    'orderMoreInventory.tips.tip1': '• Consider ordering 20% above minimum level',
    'orderMoreInventory.tips.tip2': '• Check supplier lead times before ordering',
    'orderMoreInventory.tips.tip3': '• Verify unit prices with supplier',
    'orderMoreInventory.tips.tip4': '• Add buffer time for delivery delays',
    'orderMoreInventory.tips.tip5': '• Keep order confirmation for tracking',
    'orderMoreInventory.toast.error.required': 'Please fill in all required fields',
    'orderMoreInventory.toast.error.failed': 'Failed to create purchase order. Please try again.',
    'orderMoreInventory.toast.success': 'Purchase order created successfully! Order ID: {orderId}',
    
    // Add Worker
    'addWorker.title': 'Add New Worker - {department}',
    'addWorker.subtitle': 'Add a new worker to the {description}',
    'addWorker.backToWorkers': 'Back to Workers',
    'addWorker.personalInfo': 'Personal Information',
    'addWorker.firstName': 'First Name',
    'addWorker.lastName': 'Last Name',
    'addWorker.email': 'Email Address',
    'addWorker.phone': 'Phone Number',
    'addWorker.address': 'Address',
    'addWorker.jobInfo': 'Job Information',
    'addWorker.role': 'Role',
    'addWorker.selectRole': 'Select a role',
    'addWorker.department': 'Department',
    'addWorker.employeeId': 'Employee ID',
    'addWorker.generate': 'Generate',
    'addWorker.dateOfJoining': 'Date of Joining',
    'addWorker.salary': 'Salary',
    'addWorker.status': 'Status',
    'addWorker.active': 'Active',
    'addWorker.onLeave': 'On Leave',
    'addWorker.unavailable': 'Unavailable',
    'addWorker.skillsAndNotes': 'Skills & Notes',
    'addWorker.skills': 'Skills',
    'addWorker.addSkill': 'Add Skill',
    'addWorker.commonSkills': 'Common {department} Skills',
    'addWorker.notes': 'Notes',
    'addWorker.emergencyContact': 'Emergency Contact',
    'addWorker.contactName': 'Contact Name',
    'addWorker.contactPhone': 'Contact Phone',
    'addWorker.relationship': 'Relationship',
    'addWorker.profilePicture': 'Profile Picture',
    'addWorker.uploadImage': 'Upload Image',
    'addWorker.takePhoto': 'Take Photo',
    'addWorker.saveWorker': 'Save Worker',
    'addWorker.success': '{name} has been added to {department}!',
    'addWorker.failedError': 'Failed to create worker. Please try again.',
    'addWorker.imageSizeError': 'Image size must be less than 5MB',
    'addWorker.employeeIdGenerated': 'Employee ID generated successfully',
    'addWorker.requiredFieldsError': 'Please fill in all required fields',
    'addWorker.invalidEmailError': 'Please enter a valid email address',
    
    // Add Inventory Item
    'addInventory.title': 'Add New Item',
    'addInventory.subtitle': 'Add a new item to the',
    'addInventory.backToInventory': 'Back to Inventory',
    'addInventory.basicInfo': 'Basic Information',
    'addInventory.itemName': 'Item Name',
    'addInventory.itemNamePlaceholder': 'Enter item name',
    'addInventory.category': 'Category',
    'addInventory.currentStock': 'Current Stock',
    'addInventory.minStockLevel': 'Minimum Stock Level',
    'addInventory.unit': 'Unit of Measure',
    'addInventory.sku': 'SKU',
    'addInventory.productCode': 'Product Code',
    'addInventory.skuPlaceholder': 'Enter SKU or generate',
    'addInventory.generateSku': 'Generate SKU',
    'addInventory.description': 'Description',
    'addInventory.descriptionPlaceholder': 'Describe this item...',
    'addInventory.additionalDetails': 'Additional Details',
    'addInventory.supplier': 'Supplier',
    'addInventory.supplierPlaceholder': 'Supplier name',
    'addInventory.costPrice': 'Cost Price',
    'addInventory.storageLocation': 'Storage Location',
    'addInventory.storageLocationPlaceholder': 'Warehouse section, shelf, etc.',
    'addInventory.productImage': 'Product Image',
    'addInventory.uploadImage': 'Click to upload an image',
    'addInventory.imageFormats': 'PNG, JPG, GIF up to 5MB',
    'addInventory.chooseImage': 'Choose Image',
    'addInventory.cancel': 'Cancel',
    'addInventory.addingItem': 'Adding Item...',
    'addInventory.addToInventory': 'Add to Inventory',
    'addInventory.addedTo': 'has been added to',
    'addInventory.successfully': 'successfully',
    'addInventory.requiredFieldsError': 'Please fill in all required fields',
    'addInventory.failedError': 'Failed to add item. Please try again.',
    'addInventory.imageSizeError': 'Image size must be less than 5MB',
    'addInventory.skuGenerated': 'SKU generated successfully',
    
    // Workers
    'workers.title': 'Workers Management',
    'workers.subtitle': 'Manage your team and workforce',
    'workers.addWorker': 'Add New Worker',
    'workers.totalWorkers': 'Total Workers',
    'workers.activeWorkers': 'Active Workers',
    'workers.onLeave': 'On Leave',
    'workers.departments': 'Departments',
    'workers.searchPlaceholder': 'Search workers...',
    'workers.allDepartments': 'All Departments',
    'workers.allRoles': 'All Roles',
    'workers.allStatuses': 'All Statuses',
    'workers.status.active': 'Active',
    'workers.status.inactive': 'Inactive',
    'workers.table.name': 'Name',
    'workers.table.role': 'Role',
    'workers.table.department': 'Department',
    'workers.table.salary': 'Salary',
    'workers.table.joinDate': 'Join Date',
    'workers.table.status': 'Status',
    'workers.table.actions': 'Actions',
    'workers.noWorkers': 'No workers found',
    'workers.createFirst': 'Start by adding a new worker',
    'workers.modal.addTitle': 'Add New Worker',
    'workers.modal.editTitle': 'Edit Worker',
    'workers.form.name': 'Full Name',
    'workers.form.email': 'Email',
    'workers.form.phone': 'Phone',
    'workers.form.role': 'Role',
    'workers.form.selectRole': 'Select role',
    'workers.form.department': 'Department',
    'workers.form.selectDepartment': 'Select department',
    'workers.form.salary': 'Salary',
    'workers.form.hireDate': 'Hire Date',
    'workers.form.skills': 'Skills',
    'workers.form.notes': 'Notes',
    'workers.form.create': 'Add Worker',
    'workers.form.save': 'Save Changes',
    'workers.success.create': 'Worker added successfully',
    'workers.error.create': 'Failed to add worker',
    'workers.success.update': 'Worker updated successfully',
    'workers.error.update': 'Failed to update worker',
    'workers.success.delete': 'Worker deleted successfully',
    'workers.error.delete': 'Failed to delete worker',
    'workers.success.toggleStatus': 'Worker status updated',
    'workers.error.toggleStatus': 'Failed to update worker status',
    'workers.confirm.delete': 'Are you sure you want to delete this worker?',
    'workers.confirm.deactivate': 'Are you sure you want to deactivate this worker?',
    'workers.confirm.activate': 'Are you sure you want to activate this worker?',
    
    // Analytics Translations
    'analytics.header.title': 'Analytics & Reports',
    'analytics.header.subtitle': 'Comprehensive insights and performance metrics',
    'analytics.controls.week': 'Week',
    'analytics.controls.month': 'Month',
    'analytics.controls.quarter': 'Quarter',
    'analytics.controls.year': 'Year',
    'analytics.controls.orders': 'Orders',
    'analytics.controls.revenue': 'Revenue',
    'analytics.controls.workers': 'Workers',
    'analytics.controls.tasks': 'Tasks',
    'analytics.controls.export': 'Export',
    'analytics.metrics.totalOrders': 'Total Orders',
    'analytics.metrics.totalRevenue': 'Total Revenue',
    'analytics.metrics.activeWorkers': 'Active Workers',
    'analytics.metrics.completedTasks': 'Completed Tasks',
    'analytics.metrics.fromLastMonth': 'from last month',
    'analytics.charts.monthlyOrders': 'Monthly Orders',
    'analytics.charts.departmentPerformance': 'Department Performance',
    'analytics.charts.orderStatus': 'Order Status',
    'analytics.charts.taskStatus': 'Task Status',
    'analytics.charts.completed': 'Completed',
    'analytics.charts.inProgress': 'In Progress',
    'analytics.charts.pending': 'Pending',
    'analytics.charts.overdue': 'Overdue',
    
    // Calendar Translations
    'calendar.header.title': 'Calendar & Schedule',
    'calendar.header.subtitle': 'View and manage events, tasks, and deadlines',
    'calendar.view.month': 'Month',
    'calendar.view.week': 'Week',
    'calendar.view.day': 'Day',
    'calendar.filter.all': 'All Events',
    'calendar.filter.tasks': 'Tasks',
    'calendar.filter.orders': 'Orders',
    'calendar.dayNames.sun': 'Sun',
    'calendar.dayNames.mon': 'Mon',
    'calendar.dayNames.tue': 'Tue',
    'calendar.dayNames.wed': 'Wed',
    'calendar.dayNames.thu': 'Thu',
    'calendar.dayNames.fri': 'Fri',
    'calendar.dayNames.sat': 'Sat',
    'calendar.legend.title': 'Legend',
    'calendar.legend.tasks': 'Tasks',
    'calendar.legend.orders': 'Orders',
    'calendar.legend.completed': 'Completed',
    'calendar.legend.pending': 'Pending',
    'calendar.stats.title': 'Calendar Statistics',
    'calendar.stats.pendingTasks': 'Pending Tasks',
    'calendar.stats.completedTasks': 'Completed Tasks',
    'calendar.stats.pendingOrders': 'Pending Orders',
    'calendar.stats.completedOrders': 'Completed Orders',
    'calendar.refresh': 'Refresh',

    // Roles & Permissions
    'roles.title': 'Roles & Permissions',
    'roles.subtitle': 'Manage user roles and access permissions',
    'roles.showHelp': 'Show Help',
    'roles.roles': 'Roles',
    'roles.permissionsList': 'Permissions',
    'roles.viewPermissions': 'View Permissions',
    'roles.saveChanges': 'Save Changes',
    'roles.createRole': 'Create New Role',
    'roles.editRole': 'Edit Role',
    'roles.deleteRole': 'Delete Role',
    'roles.roleName': 'Role Name',
    'roles.displayName': 'Display Name',
    'roles.description': 'Description',
    'roles.permissionsField': 'Permissions',
    'roles.isSystemRole': 'System Role',
    'roles.usersCount': 'Users Count',
    'roles.actions': 'Actions',
    'roles.confirmDelete': 'Are you sure you want to delete this role?',
    'roles.cannotDeleteSystem': 'Cannot delete system roles',
    'roles.cannotDeleteWithUsers': 'Cannot delete role with assigned users',
    'roles.roleCreated': 'Role created successfully',
    'roles.roleUpdated': 'Role updated successfully',
    'roles.roleDeleted': 'Role deleted successfully',
    'roles.loading': 'Loading roles...',
    'roles.error': 'Failed to load roles',
    'roles.noRoles': 'No roles found',
    'roles.selectPermissions': 'Select permissions for this role',
    'roles.allPermissions': 'All Permissions',
    'roles.noPermissions': 'No permissions selected',

    // Default Roles
    'roles.default.administrator': 'Administrator',
    'roles.default.administratorDesc': 'Full system access with all permissions',
    'roles.default.departmentManager': 'Department Manager',
    'roles.default.departmentManagerDesc': 'Department-specific management access',
    'roles.default.worker': 'Worker',
    'roles.default.workerDesc': 'Limited access to assigned tasks and orders',
    'roles.default.viewer': 'Viewer',
    'roles.default.viewerDesc': 'Read-only access to system data',

    // Permission Modules
    'permissions.dashboard': 'Dashboard',
    'permissions.orders': 'Orders',
    'permissions.inventory': 'Inventory',
    'permissions.workers': 'Workers',
    'permissions.clients': 'Clients',
    'permissions.production': 'Production',
    'permissions.calendar': 'Calendar',
    'permissions.analytics': 'Analytics',
    'permissions.reports': 'Reports & Analytics',
    'permissions.settings': 'Settings',
    'permissions.users': 'User Management',
    'permissions.backup': 'Backup & Restore',
    'permissions.woocommerce': 'WooCommerce Integration',

    // Permission Actions
    'permissions.view': 'View',
    'permissions.create': 'Create',
    'permissions.edit': 'Edit',
    'permissions.delete': 'Delete',
    'permissions.export': 'Export',
    'permissions.sync': 'Sync',

    // Permission Descriptions
    'permissions.dashboard.view': 'Access to view dashboard and statistics',
    'permissions.dashboard.edit': 'Ability to customize dashboard widgets and layout',
    'permissions.orders.view': 'Access to view all orders',
    'permissions.orders.create': 'Ability to create new orders',
    'permissions.orders.edit': 'Ability to modify existing orders',
    'permissions.orders.delete': 'Ability to delete orders',
    'permissions.inventory.view': 'Access to view inventory items',
    'permissions.inventory.create': 'Ability to add new inventory items',
    'permissions.inventory.edit': 'Ability to modify inventory items',
    'permissions.inventory.delete': 'Ability to delete inventory items',
    'permissions.workers.view': 'Access to view worker profiles',
    'permissions.workers.create': 'Ability to add new workers',
    'permissions.workers.edit': 'Ability to modify worker information',
    'permissions.workers.delete': 'Ability to remove workers',
    'permissions.clients.view': 'Access to view client profiles',
    'permissions.clients.create': 'Ability to add new clients',
    'permissions.clients.edit': 'Ability to modify client information',
    'permissions.clients.delete': 'Ability to remove clients',
    'permissions.production.view': 'Access to view production tracking',
    'permissions.production.edit': 'Ability to modify production stages',
    'permissions.calendar.view': 'Access to view calendar and schedules',
    'permissions.calendar.edit': 'Ability to modify calendar events',
    'permissions.analytics.view': 'Access to view analytics and statistics',
    'permissions.reports.view': 'Access to view reports and analytics',
    'permissions.reports.export': 'Ability to export reports',
    'permissions.settings.view': 'Access to view system settings',
    'permissions.settings.edit': 'Ability to modify system settings',
    'permissions.users.view': 'Access to view system users',
    'permissions.users.create': 'Ability to add new users',
    'permissions.users.edit': 'Ability to modify user information',
    'permissions.users.delete': 'Ability to remove users',
    'permissions.backup.view': 'Access to view system backups',
    'permissions.backup.create': 'Ability to create system backups',
    'permissions.backup.restore': 'Ability to restore system from backups',
    'permissions.woocommerce.view': 'Access to view WooCommerce integration',
    'permissions.woocommerce.sync': 'Ability to sync WooCommerce data',
    
    // Production Tracking Translations
    'tracking.title': 'Production Tracking',
    'tracking.subtitle': 'Monitor order progress and production stages',
    'tracking.liveUpdates': 'Live Updates',
    'tracking.orderProgress': 'Order Progress',
    'tracking.productionProgress': 'Production Progress',
    'tracking.overallProgress': 'Overall Progress',
    'tracking.client': 'Client',
    'tracking.worker': 'Worker',
    'tracking.estimated': 'Estimated',
    'tracking.actual': 'Actual',
    'tracking.station': 'Station',
    'tracking.started': 'Started',
    'production.title': 'Production Flow',
    'production.subtitle': 'Manage production stages for suits and clothing',
    'production.searchPlaceholder': 'Search orders and tasks...',
    'production.stages.all': 'All Stages',
    'production.stages.pending': 'Pending',
    'production.stages.design': 'Design',
    'production.stages.cutting': 'Cutting',
    'production.stages.sewing': 'Sewing',
    'production.stages.fitting': 'Fitting',
    'production.stages.completed': 'Completed',
    'production.stats.orders': 'orders',
    'production.stats.tasks': 'tasks',
    'production.stats.workers': 'workers',
    'production.empty.noItems': 'No items in this stage',
    'production.showMore': 'Show More',
    'production.quickActions': 'Quick Actions',
    'production.addNewOrder': 'Add New Order',
    'production.addNewTask': 'Add New Task',
    'production.manageWorkers': 'Manage Workers',
    'production.startProduction': 'Start Production',
    'production.moveToNextStage': 'Move to Next Stage',
    'production.updateStatus': 'Update Status',
    'production.assignWorker': 'Assign Worker',
    'production.productionProgress': 'Production Progress',
    'production.currentStage': 'Current Stage',
    'production.estimatedTime': 'Estimated Time',
    'production.actualTime': 'Actual Time',
    'production.worker': 'Worker',
    'production.station': 'Station',
    'production.startedAt': 'Started At',
    'production.completedAt': 'Completed At',
    'production.actions': 'Actions',
    'production.confirmStart': 'Are you sure you want to start production for this order?',
    'production.confirmMove': 'Are you sure you want to move this order to the next stage?',
    'production.confirmUpdate': 'Are you sure you want to update the status?',
    'production.success.start': 'Production started successfully',
    'production.success.move': 'Order moved to next stage successfully',
    'production.success.update': 'Status updated successfully',
    'production.error.start': 'Failed to start production',
    'production.error.move': 'Failed to move order',
    'production.error.update': 'Failed to update status',
    'production.modal.editTitle': 'Edit Order Status',
    'production.modal.stage': 'Stage',
    'production.modal.selectStage': 'Select Stage',
    'production.modal.worker': 'Worker',
    'production.modal.selectWorker': 'Select Worker',
    'production.modal.estimatedHours': 'Estimated Hours',
    'production.modal.actualHours': 'Actual Hours',
    'production.modal.notes': 'Notes',
    'production.modal.saveChanges': 'Save Changes',
    'production.modal.cancel': 'Cancel',
    'production.timeline.title': 'Production Timeline',
    'production.timeline.stage': 'Stage',
    'production.timeline.status': 'Status',
    'production.timeline.worker': 'Worker',
    'production.timeline.duration': 'Duration',
    'production.timeline.completed': 'Completed',
    'production.timeline.inProgress': 'In Progress',
    'production.timeline.pending': 'Pending',
    'stations.title': 'Station Display',
    'stations.subtitle': 'Monitor worker and task status in real-time',
    'stations.allDepartments': 'All Departments',
    'stations.gridView': 'Grid',
    'stations.listView': 'List',
    'stations.refresh': 'Refresh',
    'stations.totalWorkers': 'Total Workers',
    'stations.availableWorkers': 'Available Workers',
    'stations.activeTasks': 'Active Tasks',
    'stations.pendingOrders': 'Pending Orders',
    'stations.workerStatus': 'Worker Status',
    'stations.available': 'Available',
    'stations.busy': 'Busy',
    'stations.offline': 'Offline',
    'stations.currentTask': 'Current Task',
    'stations.noCurrentTask': 'No current task',
    'stations.assignTask': 'Assign Task',
    'stations.startTask': 'Start Task',
    'stations.completeTask': 'Complete Task',
    'stations.pauseTask': 'Pause Task',
    'stations.resumeTask': 'Resume Task',
    'stations.workerDetails': 'Worker Details',
    'stations.taskDetails': 'Task Details',
    'stations.orderDetails': 'Order Details',
    'stations.department': 'Department',
    'stations.role': 'Role',
    'stations.contact': 'Contact',
    'stations.performance': 'Performance',
    'stations.efficiency': 'Efficiency',
    'stations.completedTasks': 'Completed Tasks',
    'stations.avgTime': 'Average Time',
    'stations.quality': 'Quality Score',
    'stations.workload': 'Workload',
    'stations.capacity': 'Capacity',
    'stations.utilization': 'Utilization',
    'stations.realTimeUpdates': 'Real-time Updates',
    'stations.liveStatus': 'Live Status',
    'stations.quickActions': 'Quick Actions',
    'stations.manageWorkers': 'Manage Workers',
    'stations.viewProduction': 'View Production',
    'stations.viewTracking': 'View Tracking',
    'stations.integration': 'System Integration',
    'stations.flowConnection': 'Production Flow Connection',
    'stations.trackingConnection': 'Production Tracking Connection',
    'orders.title': 'Order Management',
    'orders.subtitle': 'View and manage all customer orders',
    'orders.newOrder': 'New Order',
    'orders.searchPlaceholder': 'Search orders...',
    'orders.allStatuses': 'All Statuses',
    'orders.status.pending': 'Pending',
    'orders.status.inProgress': 'In Progress',
    'orders.status.completed': 'Completed',
    'orders.status.cancelled': 'Cancelled',
    'orders.priority.low': 'Low',
    'orders.priority.medium': 'Medium',
    'orders.priority.high': 'High',
    'orders.priority.urgent': 'Urgent',
    'orders.date': 'Date',
    'orders.total': 'Total',
    'orders.viewDetails': 'View Details',
    'orders.orderDetails': 'Order Details',
    'orders.basicInfo': 'Basic Information',
    'orders.description': 'Description',
    'orders.status': 'Status',
    'orders.priority': 'Priority',
    'orders.clientInfo': 'Client Information',
    'orders.editOrder': 'Edit Order',
    'orders.updateOrder': 'Update Order',
    'orders.createOrder': 'Create Order',
    'orders.client': 'Client',
    'orders.category': 'Category',
    'orders.assignedWorker': 'Assigned Worker',
    'orders.startDate': 'Start Date',
    'orders.dueDate': 'Due Date',
    'orders.totalCost': 'Total Cost',
    'orders.selectClient': 'Select Client',
    'orders.selectCategory': 'Select Category',
    'orders.selectWorker': 'Select Worker',
    'orders.createSuccess': 'Order created successfully',
    'orders.updateSuccess': 'Order updated successfully',
    'orders.deleteSuccess': 'Order deleted successfully',
    'orders.deleteConfirm': 'Are you sure you want to delete this order?',
    'orders.statusUpdateSuccess': 'Order status updated successfully',
    'woocommerce.imported': 'Imported from WooCommerce',
    'woocommerce.orderDetails': 'Order Details',
    'woocommerce.orderInfo': 'Order Information',
    'woocommerce.orderNumber': 'Order Number',
    'woocommerce.status': 'Status',
    'woocommerce.dateCreated': 'Date Created',
    'woocommerce.paymentMethod': 'Payment Method',
    'woocommerce.financialInfo': 'Financial Information',
    'woocommerce.subtotal': 'Subtotal',
    'woocommerce.shipping': 'Shipping',
    'woocommerce.tax': 'Tax',
    'woocommerce.discount': 'Discount',
    'woocommerce.total': 'Total',
    'woocommerce.orderItems': 'Order Items',
    'woocommerce.quantity': 'Quantity',
    'woocommerce.billingAddress': 'Billing Address',
    'woocommerce.shippingAddress': 'Shipping Address',
    'woocommerce.status.completed': 'Completed',
    'woocommerce.status.processing': 'Processing',
    'woocommerce.status.pending': 'Pending',
    'woocommerce.status.onHold': 'On Hold',
    'woocommerce.status.cancelled': 'Cancelled',
    'woocommerce.status.refunded': 'Refunded',
    'common.close': 'Close',
    'orders.trackProduction': 'Track Production',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    
    // Workers Additional Translations
    'workers.total': 'Total Workers',
    'workers.active': 'Active Workers',
    'workers.inactive': 'Inactive Workers',
    'workers.department': 'Departments',
    'workers.table.contact': 'Contact',
    'workers.table.hireDate': 'Hire Date',
    
    // Clients Translations
    'clients.title': 'Clients Management',
    'clients.subtitle': 'Manage your customers and WooCommerce clients',
    'clients.addNew': 'Add New Client',
    'clients.total': 'Total Clients',
    'clients.woocommerce': 'WooCommerce Clients',
    'clients.local': 'Local Clients',
    'clients.searchPlaceholder': 'Search clients...',
    'clients.table.name': 'Name',
    'clients.table.email': 'Email',
    'clients.table.phone': 'Phone',
    'clients.table.address': 'Address',
    'clients.table.source': 'Source',
    'clients.table.orders': 'Orders',
    'clients.table.lastOrder': 'Last Order',
    'clients.table.actions': 'Actions',
                    'clients.source.woocommerce': 'WooCommerce',
                'clients.source.local': 'Local',
                'clients.source.all': 'All Sources',
    'clients.empty.title': 'No clients found',
    'clients.empty.subtitle': 'Start by adding a new client or sync from WooCommerce',
    'clients.syncFromWooCommerce': 'Sync from WooCommerce',
    'clients.viewProfile': 'View Profile',
    'clients.editClient': 'Edit Client',
    'clients.profile.title': 'Client Profile',
    'clients.profile.orders': 'Client Orders',
    'clients.profile.totalOrders': 'Total Orders',
    'clients.profile.totalValue': 'Total Value',
    'clients.profile.lastActivity': 'Last Activity',
    
    // Dashboard Translations
    'dashboard.header.title': 'Dashboard',
    'dashboard.header.subtitle': 'Welcome to your workshop management system',
    
    // Station Display Translations
    'station.title': 'Station Display',
    'station.subtitle': 'Monitor worker status and tasks in real-time',
    'station.filters.allDepartments': 'All Departments',
    'station.filters.grid': 'Grid',
    'station.filters.list': 'List',
    'station.filters.refresh': 'Refresh',
    'station.stats.totalWorkers': 'Total Workers',
    'station.stats.availableWorkers': 'Available Workers',
    'station.stats.activeTasks': 'Active Tasks',
    'station.stats.pendingOrders': 'Pending Orders',
    'station.worker.available': 'Available',
    'station.worker.availableForWork': 'Available for work',
    'station.worker.noCurrentTasks': 'No current tasks',
    'station.guide.title': 'Department Guide',
    'station.guide.design': 'Design',
    'station.guide.cutting': 'Cutting',
    'station.guide.sewing': 'Sewing',
    'station.guide.fitting': 'Fitting',
    'station.guide.finishing': 'Finishing',
    
    // WooCommerce Integration Translations
    'woocommerce.title': 'WooCommerce Integration',
    'woocommerce.subtitle': 'Sync products, orders, and customers from your WordPress site',
    'woocommerce.config.title': 'WooCommerce Configuration',
    'woocommerce.config.url': 'Store URL',
    'woocommerce.config.consumerKey': 'Consumer Key',
    'woocommerce.config.consumerSecret': 'Consumer Secret',
    'woocommerce.config.save': 'Save Configuration',
    'woocommerce.config.test': 'Test Connection',
    'woocommerce.sync.title': 'Data Synchronization',
    'woocommerce.sync.products': 'Sync Products',
    'woocommerce.sync.orders': 'Sync Orders',
    'woocommerce.sync.customers': 'Sync Customers',
    'woocommerce.sync.all': 'Sync All Data',
    'woocommerce.status.connected': 'Connected',
    'woocommerce.status.disconnected': 'Disconnected',
    'woocommerce.status.testing': 'Testing connection...',
    'woocommerce.status.syncing': 'Syncing data...',
    'woocommerce.success.saved': 'Configuration saved successfully',
    'woocommerce.success.connected': 'Successfully connected to WooCommerce',
    'woocommerce.success.synced': 'Data synchronized successfully',
    'woocommerce.error.connection': 'Failed to connect to WooCommerce',
    'woocommerce.error.sync': 'Failed to synchronize data',
    'woocommerce.lastSync': 'Last Sync',
    'woocommerce.never': 'Never',

    // WooCommerce Settings
    'settings.woocommerce.title': 'WooCommerce Integration',
    'settings.woocommerce.description': 'Connect and sync with your WooCommerce store',

    // Advanced Features
    'advanced.title': 'Advanced Features',
    'advanced.subtitle': 'Powerful tools for enhanced workflow management',
    'advanced.tabs.ai': 'AI & Analytics',
    'advanced.tabs.iot': 'IoT Integration',
    'advanced.tabs.system': 'System Health',
    'advanced.tabs.automation': 'Automation',

    // Automation Features
    'advanced.features.automation.title': 'Workflow Automation',
    'advanced.features.automation.description': 'Automate repetitive tasks and streamline your operations',
    'advanced.features.automation.workflowName': 'Workflow Name',
    'advanced.features.automation.trigger': 'Trigger',
    'advanced.features.automation.lastRun': 'Last Run',
    'advanced.features.automation.status': 'Status',
    'advanced.features.automation.actions': 'Actions',

    // Automation Status
    'advanced.features.automation.status.success': 'Success',
    'advanced.features.automation.status.running': 'Running',
    'advanced.features.automation.status.paused': 'Paused',
    'advanced.features.automation.status.failed': 'Failed',

    // Automation Workflows
    'advanced.features.automation.workflows.backup.name': 'Daily Backup',
    'advanced.features.automation.workflows.backup.description': 'Automated daily backup of system data',
    'advanced.features.automation.workflows.backup.trigger': 'Daily at 2:00 AM',

    'advanced.features.automation.workflows.inventory.name': 'Inventory Alert',
    'advanced.features.automation.workflows.inventory.description': 'Check inventory levels and send low stock alerts',
    'advanced.features.automation.workflows.inventory.trigger': 'Every 6 hours',

    'advanced.features.automation.workflows.completion.name': 'Order Completion',
    'advanced.features.automation.workflows.completion.description': 'Automatic order completion notification system',
    'advanced.features.automation.workflows.completion.trigger': 'On order status change',

    // Language Settings
    'settings.general.language.ltr': 'Left to Right',
    'settings.general.language.rtl': 'Right to Left',
    'settings.appearance.theme.lightDesc': 'Bright and clean',
    'settings.appearance.theme.darkDesc': 'Easy on the eyes',
    'settings.appearance.theme.autoDesc': 'Follows system preference',
  },
  ar: {
    // Common
    'common.back': 'العودة',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    
    // Navigation
    'nav.dashboard': 'لوحة القيادة',
    'nav.orders': 'الطلبات',
    'nav.inventory': 'المخزون',
    'nav.workers': 'العمال',
    'nav.calendar': 'التقويم',
    'nav.production': 'سير الإنتاج',
    'nav.stations': 'المحطات',
    'nav.analytics': 'التحليلات',
    'nav.advanced': 'الميزات المتقدمة',
    'nav.notifications': 'الإشعارات',
    'nav.settings': 'الإعدادات',
    
    // Settings Page
    'settings.title': 'الإعدادات',
    'settings.description': 'إدارة تفضيلات وتكوينات التطبيق',
    'settings.notifications.title': 'تفضيلات الإشعارات',
    'settings.notifications.description': 'تكوين كيفية تلقي الإشعارات',
    'settings.notifications.email.title': 'إشعارات البريد الإلكتروني',
    'settings.notifications.email.description': 'تلقي تحديثات الطلب والنظام عبر البريد الإلكتروني',
    'settings.notifications.email.orderUpdates': 'تحديثات الطلب',
    'settings.notifications.email.orderUpdatesDesc': 'الحصول على إشعارات حول تغييرات حالة الطلب',
    'settings.notifications.app.title': 'إشعارات داخل التطبيق',
    'settings.notifications.app.description': 'عرض الإشعارات داخل التطبيق',
    'settings.notifications.app.inApp': 'إشعارات داخل التطبيق',
    'settings.notifications.app.inAppDesc': 'عرض الإشعارات في واجهة التطبيق',
    'settings.notifications.sms.title': 'إشعارات الرسائل القصيرة',
    'settings.notifications.sms.description': 'تلقي التحديثات العاجلة عبر الرسائل القصيرة',
    'settings.notifications.sms.urgent': 'التحديثات العاجلة',
    'settings.notifications.sms.urgentDesc': 'الحصول على رسائل قصيرة للتحديثات المهمة',
    'settings.general.title': 'الإعدادات العامة',
    'settings.general.description': 'تكوين تفضيلات التطبيق',
    'settings.general.language.title': 'اللغة والمنطقة',
    'settings.general.timezone.title': 'المنطقة الزمنية',
    'settings.security.title': 'الأمان والخصوصية',
    'settings.security.description': 'إدارة إعدادات أمان حسابك',
    'settings.appearance.title': 'المظهر',
    'settings.appearance.description': 'تخصيص المظهر والشكل',
    'settings.appearance.theme.title': 'السمة',
    'settings.appearance.theme.light': '☀️ فاتح',
    'settings.appearance.theme.dark': '🌙 داكن',
    'settings.appearance.theme.auto': '🔄 تلقائي',
    'settings.appearance.theme.description': 'اختر مظهر التطبيق.',
    'settings.appearance.primaryColor.title': 'اللون الأساسي',
    'settings.appearance.primaryColor.description': 'اختر لون التمييز للواجهة.',
    'settings.appearance.preview.title': 'معاينة السمة',
    'settings.appearance.preview.description': 'شاهد كيف تبدو السمة المحددة',
    'settings.appearance.preview.cardTitle': 'بطاقة نموذجية',
    'settings.appearance.preview.cardDescription': 'هكذا ستظهر البطاقات مع السمة المختارة.',
    'settings.appearance.preview.successButton': 'زر أساسي',
    'settings.appearance.preview.secondaryButton': 'زر ثانوي',
    'settings.actions.save': 'حفظ جميع التغييرات',
    'settings.actions.reset': 'إعادة تعيين للإعدادات الافتراضية',
    'settings.actions.export': 'تصدير الإعدادات',
    
    // Dashboard
    'dashboard.title': 'لوحة القيادة',
    'dashboard.welcome': 'مرحبًا بعودتك!',
    'dashboard.overview': 'نظرة عامة على النظام',
    'dashboard.totalOrders': 'إجمالي الطلبات',
    'dashboard.activeWorkers': 'العمال النشطين',
    'dashboard.pendingTasks': 'المهام المعلقة',
    'dashboard.completedToday': 'المكتملة اليوم',
    'dashboard.revenue': 'الإيرادات الشهرية',
    'dashboard.productivity': 'الإنتاجية',
    'dashboard.recentOrders': 'الطلبات الأخيرة',
    'dashboard.quickActions': 'إجراءات سريعة',
    'dashboard.alerts': 'تنبيهات النظام',
    'dashboard.importSuccess': 'تم الاستيراد بنجاح!',
    'dashboard.importing': 'جاري الاستيراد...',
    'dashboard.importFromWooCommerce': 'استيراد من WooCommerce',
    'dashboard.additionalStats': 'إحصائيات إضافية',
    'dashboard.clients': 'العملاء',
    'dashboard.materials': 'المواد',
    'dashboard.unpaidInvoices': 'فواتير غير مدفوعة',
    'dashboard.completionRate': 'معدل الإنجاز',
    'dashboard.importResults': 'تم استيراد: {{customers}} عميل، {{products}} منتج، {{orders}} طلب',
    'dashboard.importFailed': 'فشل في استيراد البيانات من WooCommerce',
    'dashboard.orderStatus.pending': 'قيد الانتظار',
    'dashboard.orderStatus.inProgress': 'قيد التنفيذ',
    'dashboard.orderStatus.completed': 'مكتملة',
    
    // Orders
    'orders.title': 'إدارة الطلبات',
    'orders.subtitle': 'عرض وإدارة جميع طلبات العملاء',
    'orders.newOrder': 'طلب جديد',
    'orders.searchPlaceholder': 'البحث في الطلبات...',
    'orders.filter.all': 'جميع الحالات',
    'orders.filter.pending': 'قيد الانتظار',
    'orders.filter.in_progress': 'قيد التنفيذ',
    'orders.filter.completed': 'مكتمل',
    'orders.filter.cancelled': 'ملغي',
    'orders.card.worker': 'العامل: {workerName}',
    'orders.card.priority.urgent': 'عاجل',
    'orders.card.priority.high': 'عالي',
    'orders.card.priority.medium': 'متوسط',
    'orders.card.priority.low': 'منخفض',
    'orders.empty.title': 'لا توجد طلبات',
    'orders.empty.subtitle': 'ابدأ بإنشاء طلب جديد',
    'orders.createModal.title': 'إنشاء طلب جديد',
    'orders.editModal.title': 'تعديل الطلب',
    'orders.form.title.label': 'عنوان الطلب',
    'orders.form.client.label': 'العميل',
    'orders.form.client.placeholder': 'اختر العميل',
    'orders.form.category.label': 'التصنيف',
    'orders.form.category.placeholder': 'اختر التصنيف',
    'orders.form.worker.label': 'العامل المسؤول',
    'orders.form.worker.placeholder': 'اختر العامل',
    'orders.form.priority.label': 'الأولوية',
    'orders.form.cost.label': 'التكلفة',
    'orders.form.startDate.label': 'تاريخ البداية',
    'orders.form.dueDate.label': 'تاريخ التسليم',
    'orders.form.description.label': 'الوصف',
    'orders.form.createButton': 'إنشاء الطلب',
    'orders.form.updateButton': 'حفظ التغييرات',
    'orders.form.cancelButton': 'إلغاء',
    'orders.toast.createSuccess': 'تم إنشاء الطلب بنجاح.',
    'orders.toast.createError': 'خطأ في إنشاء الطلب.',
    'orders.toast.updateSuccess': 'تم تحديث الطلب بنجاح.',
    'orders.toast.updateError': 'خطأ في تحديث الطلب.',
    'orders.toast.deleteSuccess': 'تم حذف الطلب بنجاح.',
    'orders.toast.deleteError': 'خطأ في حذف الطلب.',
    'orders.toast.statusUpdateSuccess': 'تم تحديث الحالة بنجاح.',
    'orders.toast.statusUpdateError': 'خطأ في تحديث الحالة.',
    'orders.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا الطلب؟',
    'orders.status.pending': 'قيد الانتظار',
    'orders.status.in_progress': 'قيد التنفيذ',
    'orders.status.completed': 'مكتمل',
    'orders.status.cancelled': 'ملغي',
    
    // Inventory
    'inventory.title': 'إدارة المخزون',
    'inventory.subtitle': 'تتبع وإدارة المواد ومستويات المخزون الخاصة بك.',
    'inventory.addItem': 'إضافة عنصر جديد',
    'inventory.totalItems': 'إجمالي العناصر',
    'inventory.lowStock': 'مخزون منخفض',
    'inventory.outOfStock': 'نفد من المخزون',
    'inventory.stockValue': 'إجمالي قيمة المخزون',
    'inventory.searchPlaceholder': 'البحث بالاسم أو SKU...',
    'inventory.allCategories': 'جميع الفئات',
    'inventory.allStatuses': 'جميع الحالات',
    'inventory.lowStockStatus': 'مخزون منخفض',
    'inventory.outOfStockStatus': 'نفد من المخزون',
    'inventory.table.image': 'صورة',
    'inventory.table.name': 'الاسم',
    'inventory.table.sku': 'SKU',
    'inventory.table.category': 'الفئة',
    'inventory.table.quantity': 'الكمية',
    'inventory.table.status': 'الحالة',
    'inventory.table.actions': 'الإجراءات',
    'inventory.noResults': 'لم يتم العثور على مواد. حاول تعديل عوامل التصفية الخاصة بك.',
    'inventory.modal.addTitle': 'إضافة عنصر مخزون جديد',
    'inventory.modal.editTitle': 'تعديل عنصر المخزون',
    'inventory.form.name': 'اسم المادة',
    'inventory.form.category': 'الفئة',
    'inventory.form.selectCategory': 'اختر فئة',
    'inventory.form.description': 'الوصف',
    'inventory.form.sku': 'SKU (وحدة حفظ المخزون)',
    'inventory.form.unit': 'الوحدة (على سبيل المثال، متر، قطعة)',
    'inventory.form.quantity': 'الكمية المتاحة',
    'inventory.form.cost': 'التكلفة لكل وحدة',
    'inventory.form.supplier': 'المورد',
    'inventory.form.reorderLevel': 'مستوى إعادة الطلب',
    'inventory.form.location': 'موقع التخزين',
    'inventory.form.imageUrl': 'رابط الصورة',
    'common.error': 'حدث خطأ. يرجى المحاولة مرة أخرى.',
    'common.success': 'العملية ناجحة!',
    'common.deleteConfirm': 'هل أنت متأكد أنك تريد حذف هذا العنصر؟',
    'common.available': 'متوفر',
    'common.cancel': 'إلغاء',
    'common.update': 'تحديث',
    'common.save': 'حفظ',
    'invoices.title': 'إدارة الفواتير',
    'invoices.subtitle': 'إنشاء ومتابعة الفواتير والمدفوعات',
    'invoices.new': 'فاتورة جديدة',
    'invoices.total': 'إجمالي الفواتير',
    'invoices.paid': 'المبلغ المدفوع',
    'invoices.pending': 'المبلغ المعلق',
    'invoices.overdue': 'فواتير متأخرة',
    'invoices.searchPlaceholder': 'البحث في الفواتير...',
    'invoices.allStatuses': 'جميع الحالات',
    'invoices.status.draft': 'مسودة',
    'invoices.status.sent': 'مرسلة',
    'invoices.status.paid': 'مدفوعة',
    'invoices.status.overdue': 'متأخرة',
    'invoices.status.cancelled': 'ملغية',
    'invoices.issued': 'إنشاء: {date}',
    'invoices.due': 'استحقاق: {date}',
    'invoices.amount': 'المبلغ: ${amount}',
    'invoices.tax': 'الضريبة: ${amount}',
    'invoices.totalAmount': 'الإجمالي: ${amount}',
    'invoices.noInvoices': 'لا توجد فواتير',
    'invoices.createFirst': 'ابدأ بإنشاء فاتورة جديدة',
    'invoices.modal.addTitle': 'إنشاء فاتورة جديدة',
    'invoices.modal.editTitle': 'تعديل الفاتورة',
    'invoices.form.client': 'العميل',
    'invoices.form.selectClient': 'اختر العميل',
    'invoices.form.amount': 'المبلغ',
    'invoices.form.taxAmount': 'مبلغ الضريبة',
    'invoices.form.issueDate': 'تاريخ الإصدار',
    'invoices.form.dueDate': 'تاريخ الاستحقاق',
    'invoices.form.notes': 'ملاحظات',
    'invoices.form.create': 'إنشاء الفاتورة',
    'invoices.form.save': 'حفظ التغييرات',
    'invoices.error.load': 'فشل في تحميل البيانات',
    'invoices.success.create': 'تم إنشاء الفاتورة بنجاح',
    'invoices.error.create': 'فشل في إنشاء الفاتورة',
    'invoices.success.update': 'تم تحديث الفاتورة بنجاح',
    'invoices.error.update': 'فشل في تحديث الفاتورة',
    'invoices.confirm.delete': 'هل أنت متأكد من حذف هذه الفاتورة؟',
    'invoices.success.delete': 'تم حذف الفاتورة بنجاح',
    'invoices.error.delete': 'فشل في حذف الفاتورة',
    'invoices.success.statusUpdate': 'تم تحديث حالة الفاتورة',
    'invoices.error.statusUpdate': 'فشل في تحديث حالة الفاتورة',
    'notifications.title': 'إشعارات قسم {departmentName}',
    'notifications.subtitle': 'ابق على اطلاع بأنشطة {departmentDescription}',
    'notifications.all': 'الكل',
    'notifications.unread': 'غير مقروء',
    'notifications.markAllAsRead': 'وضع علامة على الكل كمقروء',
    'notifications.viewDetails': 'عرض التفاصيل',
    'notifications.markAsRead': 'وضع علامة كمقروء',
    'notifications.noNotifications': 'لم يتم العثور على إشعارات',
    'notifications.noNotificationsFor': 'لا توجد إشعارات لقسم {departmentName}',
    'orderDetails.title': 'طلب رقم #{orderId}',
    'orderDetails.subtitle': '{departmentName} • {clientName}',
    'orderDetails.print': 'طباعة',
    'orderDetails.edit': 'تعديل الطلب',
    'orderDetails.save': 'حفظ التغييرات',
    'orderDetails.backToOrders': 'العودة إلى الطلبات',
    'orderDetails.status.received': 'تم الاستلام',
    'orderDetails.status.in_progress': 'قيد التنفيذ',
    'orderDetails.status.completed': 'مكتمل',
    'orderDetails.status.cancelled': 'ملغى',
    'orderDetails.created_at': 'تم الإنشاء في {date}',
    'orderDetails.progress': 'تقدم الطلب',
    'orderDetails.tab.details': 'تفاصيل الطلب',
    'orderDetails.tab.timeline': 'الجدول الزمني',
    'orderDetails.tab.notes': 'ملاحظات',
    'orderDetails.measurements': 'القياسات',
    'orderDetails.orderInfo': 'معلومات الطلب',
    'orderDetails.productType': 'نوع المنتج',
    'orderDetails.deadline': 'الموعد النهائي',
    'orderDetails.department': 'القسم',
    'orderDetails.timeline': 'الجدول الزمني',
    'orderDetails.created': 'تم الإنشاء',
    'orderDetails.lastUpdated': 'آخر تحديث',
    'orderDetails.daysRemaining': 'الأيام المتبقية',
    'orderDetails.days': '{count} أيام',
    'orderDetails.timeline.created': 'تم إنشاء الطلب',
    'orderDetails.timeline.productionStarted': 'بدء الإنتاج',
    'orderDetails.timeline.completed': 'اكتمل الطلب',
    'orderDetails.notes.label': 'ملاحظات الطلب',
    'orderDetails.notes.placeholder': 'أضف ملاحظات حول هذا الطلب...',
    'orderDetails.notes.save': 'حفظ الملاحظات',
    'orderDetails.clientInfo': 'معلومات العميل',
    'orderDetails.clientName': 'اسم العميل',
    'orderDetails.phoneNumber': 'رقم الهاتف',
    'orderDetails.emailAddress': 'عنوان البريد الإلكتروني',
    'orderDetails.quickActions': 'إجراءات سريعة',
    'orderDetails.scheduleFitting': 'جدولة قياس',
    'orderDetails.deleteOrder': 'حذف الطلب',
    'orderDetails.stats': 'إحصائيات الطلب',
    'orderDetails.daysInProduction': 'أيام في الإنتاج',
    'orderDetails.priority': 'الأولوية',
    'orderDetails.priority.normal': 'عادي',
    'orderDetails.notFound.title': 'لم يتم العثور على الطلب',
    'orderDetails.notFound.message': 'الطلب الذي تبحث عنه غير موجود أو تم حذفه.',
    'orderDetails.toast.print': 'تم فتح مربع حوار الطباعة',
    'orderDetails.toast.updated': 'تم تحديث الطلب بنجاح',
    'orderDetails.toast.deleted': 'تم حذف الطلب بنجاح',
    'orderDetails.confirm.delete': 'هل أنت متأكد أنك تريد حذف هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.',
    
    // Order More Inventory
    'orderMoreInventory.title': 'طلب المزيد - {itemName}',
    'orderMoreInventory.subtitle': '{departmentName} • إنشاء طلب شراء',
    'orderMoreInventory.backToInventory': 'العودة إلى المخزون',
    'orderMoreInventory.notFound.title': 'العنصر غير موجود',
    'orderMoreInventory.notFound.message': 'عنصر المخزون الذي تبحث عنه غير موجود.',
    'orderMoreInventory.form.title': 'تفاصيل طلب الشراء',
    'orderMoreInventory.form.quantity': 'الكمية المطلوبة *',
    'orderMoreInventory.form.priority': 'مستوى الأولوية',
    'orderMoreInventory.form.priority.normal': 'عادي',
    'orderMoreInventory.form.priority.urgent': 'عاجل',
    'orderMoreInventory.form.priority.express': 'سريع',
    'orderMoreInventory.form.supplier': 'المورد *',
    'orderMoreInventory.form.supplier.placeholder': 'اسم المورد',
    'orderMoreInventory.form.unitPrice': 'سعر الوحدة',
    'orderMoreInventory.form.expectedDelivery': 'تاريخ التسليم المتوقع',
    'orderMoreInventory.form.notes': 'ملاحظات الطلب',
    'orderMoreInventory.form.notes.placeholder': 'أي تعليمات خاصة أو ملاحظات لهذا الطلب...',
    'orderMoreInventory.form.cancel': 'إلغاء',
    'orderMoreInventory.form.submit': 'إنشاء طلب شراء',
    'orderMoreInventory.form.submitting': 'جاري إنشاء الطلب...',
    'orderMoreInventory.summary.item.title': 'ملخص العنصر',
    'orderMoreInventory.summary.item.currentStock': 'المخزون الحالي:',
    'orderMoreInventory.summary.item.minLevel': 'الحد الأدنى:',
    'orderMoreInventory.summary.item.department': 'القسم:',
    'orderMoreInventory.summary.item.lowStock': 'تنبيه انخفاض المخزون',
    'orderMoreInventory.summary.item.lowStock.message': 'المخزون الحالي أقل من الحد الأدنى',
    'orderMoreInventory.summary.order.title': 'ملخص الطلب',
    'orderMoreInventory.summary.order.quantity': 'الكمية:',
    'orderMoreInventory.summary.order.unitPrice': 'سعر الوحدة:',
    'orderMoreInventory.summary.order.totalCost': 'التكلفة الإجمالية:',
    'orderMoreInventory.tips.title': 'نصائح للطلب',
    'orderMoreInventory.tips.tip1': '• ضع في اعتبارك طلب 20٪ فوق الحد الأدنى',
    'orderMoreInventory.tips.tip2': '• تحقق من مهل التوريد قبل الطلب',
    'orderMoreInventory.tips.tip3': '• تحقق من أسعار الوحدات مع المورد',
    'orderMoreInventory.tips.tip4': '• أضف وقتًا إضافيًا لتأخيرات التسليم',
    'orderMoreInventory.tips.tip5': '• احتفظ بتأكيد الطلب للتتبع',
    'orderMoreInventory.toast.error.required': 'يرجى ملء جميع الحقول المطلوبة',
    'orderMoreInventory.toast.error.failed': 'فشل إنشاء طلب الشراء. يرجى المحاولة مرة أخرى.',
    'orderMoreInventory.toast.success': 'تم إنشاء طلب الشراء بنجاح! رقم الطلب: {orderId}',
    
    // Add Worker
    'addWorker.title': 'إضافة عامل جديد - {department}',
    'addWorker.subtitle': 'إضافة عامل جديد إلى {description}',
    'addWorker.backToWorkers': 'العودة إلى العمال',
    'addWorker.personalInfo': 'المعلومات الشخصية',
    'addWorker.firstName': 'الاسم الأول',
    'addWorker.lastName': 'اسم العائلة',
    'addWorker.email': 'عنوان البريد الإلكتروني',
    'addWorker.phone': 'رقم الهاتف',
    'addWorker.address': 'العنوان',
    'addWorker.jobInfo': 'معلومات الوظيفة',
    'addWorker.role': 'الدور',
    'addWorker.selectRole': 'اختر دورًا',
    'addWorker.department': 'القسم',
    'addWorker.employeeId': 'رقم الموظف',
    'addWorker.generate': 'إنشاء',
    'addWorker.dateOfJoining': 'تاريخ الانضمام',
    'addWorker.salary': 'الراتب',
    'addWorker.status': 'الحالة',
    'addWorker.active': 'نشط',
    'addWorker.onLeave': 'في إجازة',
    'addWorker.unavailable': 'غير متاح',
    'addWorker.skillsAndNotes': 'المهارات والملاحظات',
    'addWorker.skills': 'المهارات',
    'addWorker.addSkill': 'إضافة مهارة',
    'addWorker.commonSkills': 'مهارات {department} الشائعة',
    'addWorker.notes': 'ملاحظات',
    'addWorker.emergencyContact': 'جهة الاتصال الطارئة',
    'addWorker.contactName': 'اسم جهة الاتصال',
    'addWorker.contactPhone': 'هاتف جهة الاتصال',
    'addWorker.relationship': 'العلاقة',
    'addWorker.profilePicture': 'صورة الملف الشخصي',
    'addWorker.uploadImage': 'رفع صورة',
    'addWorker.takePhoto': 'التقاط صورة',
    'addWorker.saveWorker': 'حفظ العامل',
    'addWorker.success': 'تم إضافة {name} إلى {department}!',
    'addWorker.failedError': 'فشل في إنشاء العامل. يرجى المحاولة مرة أخرى.',
    'addWorker.imageSizeError': 'يجب أن يكون حجم الصورة أقل من 5 ميجابايت',
    'addWorker.employeeIdGenerated': 'تم إنشاء رقم الموظف بنجاح',
    'addWorker.requiredFieldsError': 'يرجى ملء جميع الحقول المطلوبة',
    'addWorker.invalidEmailError': 'يرجى إدخال عنوان بريد إلكتروني صحيح',
    
    // Add Inventory Item
    'addInventory.title': 'إضافة عنصر جديد',
    'addInventory.subtitle': 'إضافة عنصر جديد إلى',
    'addInventory.backToInventory': 'العودة إلى المخزون',
    'addInventory.basicInfo': 'المعلومات الأساسية',
    'addInventory.itemName': 'اسم العنصر',
    'addInventory.itemNamePlaceholder': 'أدخل اسم العنصر',
    'addInventory.category': 'الفئة',
    'addInventory.currentStock': 'المخزون الحالي',
    'addInventory.minStockLevel': 'الحد الأدنى للمخزون',
    'addInventory.unit': 'وحدة القياس',
    'addInventory.sku': 'رمز المنتج',
    'addInventory.productCode': 'كود المنتج',
    'addInventory.skuPlaceholder': 'أدخل رمز المنتج أو قم بإنشائه',
    'addInventory.generateSku': 'إنشاء رمز المنتج',
    'addInventory.description': 'الوصف',
    'addInventory.descriptionPlaceholder': 'صف هذا العنصر...',
    'addInventory.additionalDetails': 'تفاصيل إضافية',
    'addInventory.supplier': 'المورد',
    'addInventory.supplierPlaceholder': 'اسم المورد',
    'addInventory.costPrice': 'سعر التكلفة',
    'addInventory.storageLocation': 'موقع التخزين',
    'addInventory.storageLocationPlaceholder': 'قسم المستودع، الرف، إلخ.',
    'addInventory.productImage': 'صورة المنتج',
    'addInventory.uploadImage': 'انقر لرفع صورة',
    'addInventory.imageFormats': 'PNG، JPG، GIF حتى 5 ميجابايت',
    'addInventory.chooseImage': 'اختر صورة',
    'addInventory.cancel': 'إلغاء',
    'addInventory.addingItem': 'جاري إضافة العنصر...',
    'addInventory.addToInventory': 'إضافة إلى المخزون',
    'addInventory.addedTo': 'تم إضافته إلى',
    'addInventory.successfully': 'بنجاح',
    'addInventory.requiredFieldsError': 'يرجى ملء جميع الحقول المطلوبة',
    'addInventory.failedError': 'فشل في إضافة العنصر. يرجى المحاولة مرة أخرى.',
    'addInventory.imageSizeError': 'يجب أن يكون حجم الصورة أقل من 5 ميجابايت',
    'addInventory.skuGenerated': 'تم إنشاء رمز المنتج بنجاح',
    
    // Workers
    'workers.title': 'إدارة العمال',
    'workers.subtitle': 'إدارة فريقك والقوى العاملة',
    'workers.addWorker': 'إضافة عامل جديد',
    'workers.totalWorkers': 'إجمالي العمال',
    'workers.activeWorkers': 'العمال النشطون',
    'workers.onLeave': 'في إجازة',
    'workers.departments': 'الأقسام',
    'workers.searchPlaceholder': 'البحث في العمال...',
    'workers.allDepartments': 'جميع الأقسام',
    'workers.allRoles': 'جميع الأدوار',
    'workers.allStatuses': 'جميع الحالات',
    'workers.status.active': 'نشط',
    'workers.status.inactive': 'غير نشط',
    'workers.table.name': 'الاسم',
    'workers.table.role': 'الدور',
    'workers.table.department': 'القسم',
    'workers.table.salary': 'الراتب',
    'workers.table.joinDate': 'تاريخ الانضمام',
    'workers.table.status': 'الحالة',
    'workers.table.actions': 'الإجراءات',
    'workers.noWorkers': 'لم يتم العثور على عمال',
    'workers.createFirst': 'ابدأ بإضافة عامل جديد',
    'workers.modal.addTitle': 'إضافة عامل جديد',
    'workers.modal.editTitle': 'تعديل العامل',
    'workers.form.name': 'الاسم الكامل',
    'workers.form.email': 'البريد الإلكتروني',
    'workers.form.phone': 'الهاتف',
    'workers.form.role': 'الدور',
    'workers.form.selectRole': 'اختر الدور',
    'workers.form.department': 'القسم',
    'workers.form.selectDepartment': 'اختر القسم',
    'workers.form.salary': 'الراتب',
    'workers.form.hireDate': 'تاريخ التوظيف',
    'workers.form.skills': 'المهارات',
    'workers.form.notes': 'ملاحظات',
    'workers.form.create': 'إضافة عامل',
    'workers.form.save': 'حفظ التغييرات',
    'workers.success.create': 'تم إضافة العامل بنجاح',
    'workers.error.create': 'فشل في إضافة العامل',
    'workers.success.update': 'تم تحديث العامل بنجاح',
    'workers.error.update': 'فشل في تحديث العامل',
    'workers.success.delete': 'تم حذف العامل بنجاح',
    'workers.error.delete': 'فشل في حذف العامل',
    'workers.success.toggleStatus': 'تم تحديث حالة العامل',
    'workers.error.toggleStatus': 'فشل في تحديث حالة العامل',
    'workers.confirm.delete': 'هل أنت متأكد من حذف هذا العامل؟',
    'workers.confirm.deactivate': 'هل أنت متأكد من إلغاء تنشيط هذا العامل؟',
    'workers.confirm.activate': 'هل أنت متأكد من تنشيط هذا العامل؟',
    
    // Analytics Translations
    'analytics.header.title': 'التحليلات والتقارير',
    'analytics.header.subtitle': 'رؤى شاملة ومقاييس الأداء',
    'analytics.controls.week': 'أسبوع',
    'analytics.controls.month': 'شهر',
    'analytics.controls.quarter': 'ربع سنة',
    'analytics.controls.year': 'سنة',
    'analytics.controls.orders': 'الطلبات',
    'analytics.controls.revenue': 'الإيرادات',
    'analytics.controls.workers': 'العمال',
    'analytics.controls.tasks': 'المهام',
    'analytics.controls.export': 'تصدير',
    'analytics.metrics.totalOrders': 'إجمالي الطلبات',
    'analytics.metrics.totalRevenue': 'إجمالي الإيرادات',
    'analytics.metrics.activeWorkers': 'العمال النشطون',
    'analytics.metrics.completedTasks': 'المهام المكتملة',
    'analytics.metrics.fromLastMonth': 'من الشهر الماضي',
    'analytics.charts.monthlyOrders': 'الطلبات الشهرية',
    'analytics.charts.departmentPerformance': 'أداء الأقسام',
    'analytics.charts.orderStatus': 'حالة الطلبات',
    'analytics.charts.taskStatus': 'حالة المهام',
    'analytics.charts.completed': 'مكتمل',
    'analytics.charts.inProgress': 'قيد التنفيذ',
    'analytics.charts.pending': 'معلق',
    'analytics.charts.overdue': 'متأخر',
    
    // Calendar Translations
    'calendar.header.title': 'التقويم والجدولة',
    'calendar.header.subtitle': 'عرض وإدارة الأحداث والمهام والمواعيد النهائية',
    'calendar.view.month': 'الشهر',
    'calendar.view.week': 'الأسبوع',
    'calendar.view.day': 'اليوم',
    'calendar.filter.all': 'جميع الأحداث',
    'calendar.filter.tasks': 'المهام',
    'calendar.filter.orders': 'الطلبات',
    'calendar.dayNames.sun': 'الأحد',
    'calendar.dayNames.mon': 'الاثنين',
    'calendar.dayNames.tue': 'الثلاثاء',
    'calendar.dayNames.wed': 'الأربعاء',
    'calendar.dayNames.thu': 'الخميس',
    'calendar.dayNames.fri': 'الجمعة',
    'calendar.dayNames.sat': 'السبت',
    'calendar.legend.title': 'دليل الألوان',
    'calendar.legend.tasks': 'المهام',
    'calendar.legend.orders': 'الطلبات',
    'calendar.legend.completed': 'مكتمل',
    'calendar.legend.pending': 'معلق',
    'calendar.stats.title': 'إحصائيات التقويم',
    'calendar.stats.pendingTasks': 'المهام المعلقة',
    'calendar.stats.completedTasks': 'المهام المكتملة',
    'calendar.stats.pendingOrders': 'الطلبات المعلقة',
    'calendar.stats.completedOrders': 'الطلبات المكتملة',
    'calendar.refresh': 'تحديث',
    
    // Production Tracking Translations
    'tracking.title': 'تتبع الإنتاج',
    'tracking.subtitle': 'مراقبة تقدم الطلبات ومراحل الإنتاج',
    'tracking.liveUpdates': 'التحديثات المباشرة',
    'tracking.orderProgress': 'تقدم الطلب',
    'tracking.productionProgress': 'تقدم الإنتاج',
    'tracking.overallProgress': 'التقدم الإجمالي',
    'tracking.client': 'العميل',
    'tracking.worker': 'العامل',
    'tracking.estimated': 'المقدر',
    'tracking.actual': 'الفعلي',
    'tracking.station': 'المحطة',
    'tracking.started': 'بدأ في',
    'production.title': 'سير الإنتاج',
    'production.subtitle': 'إدارة مراحل إنتاج البدلات والملابس',
    'production.searchPlaceholder': 'البحث في الطلبات والمهام...',
    'production.stages.all': 'جميع المراحل',
    'production.stages.pending': 'قيد الانتظار',
    'production.stages.design': 'التصميم',
    'production.stages.cutting': 'القطع',
    'production.stages.sewing': 'الخياطة',
    'production.stages.fitting': 'التركيب',
    'production.stages.completed': 'مكتمل',
    'production.stats.orders': 'طلب',
    'production.stats.tasks': 'مهمة',
    'production.stats.workers': 'عامل',
    'production.empty.noItems': 'لا توجد عناصر في هذه المرحلة',
    'production.showMore': 'عرض المزيد',
    'production.quickActions': 'إجراءات سريعة',
    'production.addNewOrder': 'إضافة طلب جديد',
    'production.addNewTask': 'إضافة مهمة جديدة',
    'production.manageWorkers': 'إدارة العمال',
    'production.startProduction': 'بدء الإنتاج',
    'production.moveToNextStage': 'الانتقال للمرحلة التالية',
    'production.updateStatus': 'تحديث الحالة',
    'production.assignWorker': 'تعيين عامل',
    'production.productionProgress': 'تقدم الإنتاج',
    'production.currentStage': 'المرحلة الحالية',
    'production.estimatedTime': 'الوقت المتوقع',
    'production.actualTime': 'الوقت الفعلي',
    'production.worker': 'العامل',
    'production.station': 'المحطة',
    'production.startedAt': 'تاريخ البدء',
    'production.completedAt': 'تاريخ الإنجاز',
    'production.actions': 'الإجراءات',
    'production.confirmStart': 'هل أنت متأكد من بدء الإنتاج لهذا الطلب؟',
    'production.confirmMove': 'هل أنت متأكد من نقل هذا الطلب للمرحلة التالية؟',
    'production.confirmUpdate': 'هل أنت متأكد من تحديث الحالة؟',
    'production.success.start': 'تم بدء الإنتاج بنجاح',
    'production.success.move': 'تم نقل الطلب للمرحلة التالية بنجاح',
    'production.success.update': 'تم تحديث الحالة بنجاح',
    'production.error.start': 'فشل في بدء الإنتاج',
    'production.error.move': 'فشل في نقل الطلب',
    'production.error.update': 'فشل في تحديث الحالة',
    'production.modal.editTitle': 'تعديل حالة الطلب',
    'production.modal.stage': 'المرحلة',
    'production.modal.selectStage': 'اختر المرحلة',
    'production.modal.worker': 'العامل',
    'production.modal.selectWorker': 'اختر العامل',
    'production.modal.estimatedHours': 'الساعات المتوقعة',
    'production.modal.actualHours': 'الساعات الفعلية',
    'production.modal.notes': 'ملاحظات',
    'production.modal.saveChanges': 'حفظ التغييرات',
    'production.modal.cancel': 'إلغاء',
    'production.timeline.title': 'جدول زمني للإنتاج',
    'production.timeline.stage': 'المرحلة',
    'production.timeline.status': 'الحالة',
    'production.timeline.worker': 'العامل',
    'production.timeline.duration': 'المدة',
    'production.timeline.completed': 'مكتمل',
    'production.timeline.inProgress': 'قيد التنفيذ',
    'production.timeline.pending': 'قيد الانتظار',
    'stations.title': 'عرض المحطات',
    'stations.subtitle': 'مراقبة حالة العمال والمهام في الوقت الفعلي',
    'stations.allDepartments': 'جميع الأقسام',
    'stations.gridView': 'شبكة',
    'stations.listView': 'قائمة',
    'stations.refresh': 'تحديث',
    'stations.totalWorkers': 'إجمالي العمال',
    'stations.availableWorkers': 'العمال المتاحون',
    'stations.activeTasks': 'المهام النشطة',
    'stations.pendingOrders': 'الطلبات المعلقة',
    'stations.workerStatus': 'حالة العامل',
    'stations.available': 'متاح',
    'stations.busy': 'مشغول',
    'stations.offline': 'غير متصل',
    'stations.currentTask': 'المهمة الحالية',
    'stations.noCurrentTask': 'لا توجد مهام حالية',
    'stations.assignTask': 'تعيين مهمة',
    'stations.startTask': 'بدء المهمة',
    'stations.completeTask': 'إكمال المهمة',
    'stations.pauseTask': 'إيقاف مؤقت',
    'stations.resumeTask': 'استئناف المهمة',
    'stations.workerDetails': 'تفاصيل العامل',
    'stations.taskDetails': 'تفاصيل المهمة',
    'stations.orderDetails': 'تفاصيل الطلب',
    'stations.department': 'القسم',
    'stations.role': 'الدور',
    'stations.contact': 'معلومات الاتصال',
    'stations.performance': 'الأداء',
    'stations.efficiency': 'الكفاءة',
    'stations.completedTasks': 'المهام المكتملة',
    'stations.avgTime': 'متوسط الوقت',
    'stations.quality': 'جودة العمل',
    'stations.workload': 'عبء العمل',
    'stations.capacity': 'القدرة',
    'stations.utilization': 'معدل الاستخدام',
    'stations.realTimeUpdates': 'تحديثات فورية',
    'stations.liveStatus': 'الحالة المباشرة',
    'stations.quickActions': 'إجراءات سريعة',
    'stations.manageWorkers': 'إدارة العمال',
    'stations.viewProduction': 'عرض الإنتاج',
    'stations.viewTracking': 'عرض التتبع',
    'stations.integration': 'تكامل النظام',
    'stations.flowConnection': 'ربط سير الإنتاج',
    'stations.trackingConnection': 'ربط تتبع الإنتاج',
    'orders.title': 'إدارة الطلبات',
    'orders.subtitle': 'عرض وإدارة جميع طلبات العملاء',
    'orders.newOrder': 'طلب جديد',
    'orders.searchPlaceholder': 'البحث في الطلبات...',
    'orders.allStatuses': 'جميع الحالات',
    'orders.status.pending': 'قيد الانتظار',
    'orders.status.inProgress': 'قيد التنفيذ',
    'orders.status.completed': 'مكتمل',
    'orders.status.cancelled': 'ملغي',
    'orders.priority.low': 'منخفض',
    'orders.priority.medium': 'متوسط',
    'orders.priority.high': 'عالي',
    'orders.priority.urgent': 'عاجل',
    'orders.date': 'التاريخ',
    'orders.total': 'الإجمالي',
    'orders.viewDetails': 'عرض التفاصيل',
    'orders.orderDetails': 'تفاصيل الطلب',
    'orders.basicInfo': 'المعلومات الأساسية',
    'orders.description': 'الوصف',
    'orders.status': 'الحالة',
    'orders.priority': 'الأولوية',
    'orders.clientInfo': 'معلومات العميل',
    'orders.editOrder': 'تعديل الطلب',
    'orders.updateOrder': 'تحديث الطلب',
    'orders.createOrder': 'إنشاء الطلب',
    'orders.client': 'العميل',
    'orders.category': 'التصنيف',
    'orders.assignedWorker': 'العامل المسؤول',
    'orders.startDate': 'تاريخ البداية',
    'orders.dueDate': 'تاريخ التسليم',
    'orders.totalCost': 'التكلفة الإجمالية',
    'orders.selectClient': 'اختر العميل',
    'orders.selectCategory': 'اختر التصنيف',
    'orders.selectWorker': 'اختر العامل',
    'orders.createSuccess': 'تم إنشاء الطلب بنجاح',
    'orders.updateSuccess': 'تم تحديث الطلب بنجاح',
    'orders.deleteSuccess': 'تم حذف الطلب بنجاح',
    'orders.deleteConfirm': 'هل أنت متأكد من حذف هذا الطلب؟',
    'orders.statusUpdateSuccess': 'تم تحديث حالة الطلب بنجاح',
    'woocommerce.imported': 'مستورد من WooCommerce',
    'woocommerce.orderDetails': 'تفاصيل الطلب',
    'woocommerce.orderInfo': 'معلومات الطلب',
    'woocommerce.orderNumber': 'رقم الطلب',
    'woocommerce.status': 'الحالة',
    'woocommerce.dateCreated': 'تاريخ الإنشاء',
    'woocommerce.paymentMethod': 'طريقة الدفع',
    'woocommerce.financialInfo': 'المعلومات المالية',
    'woocommerce.subtotal': 'المجموع الفرعي',
    'woocommerce.shipping': 'الشحن',
    'woocommerce.tax': 'الضريبة',
    'woocommerce.discount': 'الخصم',
    'woocommerce.total': 'الإجمالي',
    'woocommerce.orderItems': 'عناصر الطلب',
    'woocommerce.quantity': 'الكمية',
    'woocommerce.billingAddress': 'عنوان الفواتير',
    'woocommerce.shippingAddress': 'عنوان الشحن',
    'woocommerce.status.completed': 'مكتمل',
    'woocommerce.status.processing': 'قيد المعالجة',
    'woocommerce.status.pending': 'قيد الانتظار',
    'woocommerce.status.onHold': 'معلق',
    'woocommerce.status.cancelled': 'ملغي',
    'woocommerce.status.refunded': 'مسترد',
    'common.close': 'إغلاق',
    'orders.trackProduction': 'متابعة الإنتاج',
    'common.edit': 'تعديل',
    'common.view': 'عرض',
    'common.delete': 'حذف',
    'common.save': 'حفظ',
    'common.cancel': 'إلغاء',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.search': 'بحث',
    'common.filter': 'تصفية',
    'common.refresh': 'تحديث',
    'common.loading': 'جاري التحميل...',
    'common.error': 'حدث خطأ',
    'common.success': 'تم بنجاح',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    
    // Workers Additional Translations
    'workers.total': 'إجمالي العمال',
    'workers.active': 'العمال النشطون',
    'workers.inactive': 'العمال غير النشطين',
    'workers.department': 'الأقسام',
    'workers.table.contact': 'جهة الاتصال',
    'workers.table.hireDate': 'تاريخ التوظيف',
    
    // Clients Translations
    'clients.title': 'إدارة العملاء',
    'clients.subtitle': 'إدارة عملائك وعملاء ووكومرس',
    'clients.addNew': 'إضافة عميل جديد',
    'clients.total': 'إجمالي العملاء',
    'clients.woocommerce': 'عملاء ووكومرس',
    'clients.local': 'عملاء محليون',
    'clients.searchPlaceholder': 'البحث في العملاء...',
    'clients.table.name': 'الاسم',
    'clients.table.email': 'الإيميل',
    'clients.table.phone': 'الهاتف',
    'clients.table.address': 'العنوان',
    'clients.table.source': 'المصدر',
    'clients.table.orders': 'الطلبات',
    'clients.table.lastOrder': 'آخر طلب',
    'clients.table.actions': 'الإجراءات',
    'clients.source.woocommerce': 'ووكومرس',
    'clients.source.local': 'محلي',
    'clients.empty.title': 'لا يوجد عملاء',
    'clients.empty.subtitle': 'ابدأ بإضافة عميل جديد أو قم بالمزامنة من ووكومرس',
    'clients.syncFromWooCommerce': 'مزامنة من ووكومرس',
                    'clients.viewProfile': 'عرض الملف الشخصي',
                'clients.editClient': 'تعديل العميل',
    'clients.profile.title': 'ملف العميل',
    'clients.profile.orders': 'طلبات العميل',
    'clients.profile.totalOrders': 'إجمالي الطلبات',
    'clients.profile.totalValue': 'إجمالي القيمة',
    'clients.profile.lastActivity': 'آخر نشاط',
    
    // Dashboard Translations
    'dashboard.header.title': 'لوحة القيادة',
    'dashboard.header.subtitle': 'مرحباً بك في نظام إدارة الورشة',
    
    // Station Display Translations
    'station.title': 'عرض المحطات',
    'station.subtitle': 'مراقبة حالة العمال والمهام في الوقت الفعلي',
    'station.filters.allDepartments': 'جميع الأقسام',
    'station.filters.grid': 'شبكة',
    'station.filters.list': 'قائمة',
    'station.filters.refresh': 'تحديث',
    'station.stats.totalWorkers': 'إجمالي العمال',
    'station.stats.availableWorkers': 'العمال المتاحون',
    'station.stats.activeTasks': 'المهام النشطة',
    'station.stats.pendingOrders': 'الطلبات المعلقة',
    'station.worker.available': 'متاح',
    'station.worker.availableForWork': 'متاح للعمل',
    'station.worker.noCurrentTasks': 'لا توجد مهام حالية',
    'station.guide.title': 'دليل الأقسام',
    'station.guide.design': 'التصميم',
    'station.guide.cutting': 'القطع',
    'station.guide.sewing': 'الخياطة',
    'station.guide.fitting': 'التركيب',
    'station.guide.finishing': 'التشطيب',
    
    // WooCommerce Integration Translations
    'woocommerce.title': 'تكامل ووكومرس',
    'woocommerce.subtitle': 'مزامنة المنتجات والطلبات والعملاء من موقع WordPress',
    'woocommerce.config.title': 'إعدادات ووكومرس',
    'woocommerce.config.url': 'رابط المتجر',
    'woocommerce.config.consumerKey': 'مفتاح المستهلك',
    'woocommerce.config.consumerSecret': 'سر المستهلك',
    'woocommerce.config.save': 'حفظ الإعدادات',
    'woocommerce.config.test': 'اختبار الاتصال',
    'woocommerce.sync.title': 'مزامنة البيانات',
    'woocommerce.sync.products': 'مزامنة المنتجات',
    'woocommerce.sync.orders': 'مزامنة الطلبات',
    'woocommerce.sync.customers': 'مزامنة العملاء',
    'woocommerce.sync.all': 'مزامنة جميع البيانات',
    'woocommerce.status.connected': 'متصل',
    'woocommerce.status.disconnected': 'غير متصل',
    'woocommerce.status.testing': 'جاري اختبار الاتصال...',
    'woocommerce.status.syncing': 'جاري مزامنة البيانات...',
    'woocommerce.success.saved': 'تم حفظ الإعدادات بنجاح',
    'woocommerce.success.connected': 'تم الاتصال بووكومرس بنجاح',
    'woocommerce.success.synced': 'تم مزامنة البيانات بنجاح',
    'woocommerce.error.connection': 'فشل في الاتصال بووكومرس',
    'woocommerce.error.sync': 'فشل في مزامنة البيانات',
    'woocommerce.lastSync': 'آخر مزامنة',
    'woocommerce.never': 'لم يتم',

    // WooCommerce Settings
    'settings.woocommerce.title': 'تكامل WooCommerce',
    'settings.woocommerce.description': 'ربط ومزامنة متجر WooCommerce الخاص بك',

    // Advanced Features
    'advanced.title': 'الميزات المتقدمة',
    'advanced.subtitle': 'أدوات قوية لإدارة سير العمل المحسن',
    'advanced.tabs.ai': 'الذكاء الاصطناعي والتحليلات',
    'advanced.tabs.iot': 'تكامل إنترنت الأشياء',
    'advanced.tabs.system': 'صحة النظام',
    'advanced.tabs.automation': 'الأتمتة',

    // Automation Features
    'advanced.features.automation.title': 'أتمتة سير العمل',
    'advanced.features.automation.description': 'أتمتة المهام المتكررة وتبسيط العمليات',
    'advanced.features.automation.workflowName': 'اسم سير العمل',
    'advanced.features.automation.trigger': 'المحفز',
    'advanced.features.automation.lastRun': 'آخر تشغيل',
    'advanced.features.automation.status': 'الحالة',
    'advanced.features.automation.actions': 'الإجراءات',

    // Automation Status
    'advanced.features.automation.status.success': 'نجح',
    'advanced.features.automation.status.running': 'قيد التشغيل',
    'advanced.features.automation.status.paused': 'متوقف مؤقتاً',
    'advanced.features.automation.status.failed': 'فشل',

    // Automation Workflows
    'advanced.features.automation.workflows.backup.name': 'النسخ الاحتياطي اليومي',
    'advanced.features.automation.workflows.backup.description': 'نسخ احتياطي تلقائي يومي لبيانات النظام',
    'advanced.features.automation.workflows.backup.trigger': 'يومياً في الساعة 2:00 صباحاً',

    'advanced.features.automation.workflows.inventory.name': 'تنبيه المخزون',
    'advanced.features.automation.workflows.inventory.description': 'فحص مستويات المخزون وإرسال تنبيهات انخفاض المخزون',
    'advanced.features.automation.workflows.inventory.trigger': 'كل 6 ساعات',

    'advanced.features.automation.workflows.completion.name': 'إكمال الطلب',
    'advanced.features.automation.workflows.completion.description': 'نظام إشعار إكمال الطلب التلقائي',
    'advanced.features.automation.workflows.completion.trigger': 'عند تغيير حالة الطلب',

    // Language Settings
    'settings.general.language.ltr': 'من اليسار إلى اليمين',
    'settings.general.language.rtl': 'من اليمين إلى اليسار',
    'settings.appearance.theme.lightDesc': 'مشرق ونظيف',
    'settings.appearance.theme.darkDesc': 'مريح للعيون',
    'settings.appearance.theme.autoDesc': 'يتبع تفضيل النظام',
  }
};

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Load saved language from localStorage or default to English
    const savedLanguage = localStorage.getItem('app_language') as Language;
    setLanguage(savedLanguage || 'en');
  }, []);

  const t = (key: string, options?: { [key: string]: string | number }): string => {
    const langTranslations = translations[language];
    const translation = (langTranslations as any)[key] || key;
    if (!options) return translation;

    return translation.replace(/{{(\w+)}}/g, (_: string, k: string) => String(options![k]));
  };

  const isRTL = language === 'ar';

  const value = { language, setLanguage, t, isRTL };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}